version: "3.9"

services:
  # ───────────── L4 ─────────────
  haproxy-l4:
    image: haproxy:latest
    container_name: haproxy_l4
    volumes:
      - ./haproxy/l4/haproxy-l4.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
    depends_on:
      - haproxy-l7-1
      - haproxy-l7-2

  # ───────────── L7 NODE 1 ─────────────
  haproxy-l7-1:
    image: haproxy:latest
    container_name: haproxy_l7_1
    volumes:
      - ./haproxy/l7/haproxy-l7.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8405:8404"
    depends_on:
      - fe1
      - fe2
      - be1
      - be2

  # ───────────── L7 NODE 2 ─────────────
  haproxy-l7-2:
    image: haproxy:latest
    container_name: haproxy_l7_2
    volumes:
      - ./haproxy/l7/haproxy-l7.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8406:8404"
    depends_on:
      - fe1
      - fe2
      - be1
      - be2

  # ───────────── FE DEV ─────────────
  fe1:
    build: ./frontend
    container_name: fe1
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  fe2:
    build: ./frontend
    container_name: fe2
    ports:
      - "3002:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  # ───────────── BE DEV ─────────────
  be1:
    build: ./backend
    container_name: be1
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  be2:
    build: ./backend
    container_name: be2
    ports:
      - "5002:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  default:
    driver: bridge
